questions =  [
    {"id": 0, "question": "Celowo denerwuję ludzi w internecie.", "effects": {"right": -2}},
    {"id": 1, "question": "Staram się celowo tworzyć kłótnie w sieci.", "effects": {"right": -2}},
    {"id": 2, "question": "Celowo wyrażam zdanie odmienne od zdania ogółu strony/forum, by wywołać kłotnie bądź fale nieprzychylnych komentarzy/opinii.", "effects": {"right": -2}},
    {"id": 3, "question": "Zdarza mi się pisać komentarze z losowymi słowami.", "effects": {"auth": -1}},
    {"id": 4, "question": "Zdarza mi się tworzyć multikonta do trollowania.", "effects": {"right": -1}},

    {"id": 5, "question": "Trolle zazwyczaj są bardziej żenujące niż denerwujące, choć ich celem jest właśnie denerwowanie innych.", "effects": {"right": 2}},

    {"id": 6, "question": "Moimi komentarzami daję do zrozumienia, że nie pisze na poważnie.", "effects": {"auth": -3}},
    {"id": 7, "question": "Mam pogardliwy stosunek wobec dyskutantów w sieci.", "effects": {"right": -2}},
    {"id": 8, "question": "Czy odpowiednim jest użycie celowych błędów ortograficznych, aby zwiększyć skuteczność trollingu lub baitowania?", "effects": {"prog": -2}},
    {"id": 9, "question": "Czy błędy ortograficzne są dla ciebie szczególnie rażące?", "effects": {"prog": 2}},
    {"id": 10, "question": "Czy atakujesz innych użytkowników za najdrobniejsze literówki?", "effects": {"prog": 2}},
    {"id": 11, "question": "Czy troll po zostaniu wykrytym, powinien uznać to jako porażkę?", "effects": {"auth": 1}},
    {"id": 12, "question": "Moje komentarze są przepełnione sarkazmem i ironią.", "effects": {"auth": -1}},
    {"id": 13, "question": "Pisze niepoważne komentarze, lecz trollingiem bym tego nie nazwał.", "effects": {"auth": -1}},
    {"id": 14, "question": "Każdy niepoważny użytkownik to troll.", "effects": {"auth": 1}},
    {"id": 15, "question": "Użytkownicy dookoła mnie piszą masę komentarzy pozbawionych sensu i nie jestem w stanie zrozumieć, po co to robią.", "effects": {"auth": 2}},
    {"id": 16, "question": "Nadużywanie emoji jest ok, jeśli robimy to ironicznie.", "effects": {"auth": -1}},
    {"id": 17, "question": "Nie widzę sensu w używaniu poprawnej gramatyki, ortografii i interpunkcji.", "effects": {"prog": -1}},
    {"id": 18, "question": "Nie używam polskich znaków podczas pisania w internecie.", "effects": {"prog": -2}},
    {"id": 19, "question": "Nie zaczynam zdań wielką literą w internecie.", "effects": {"prog": -1}},
    {"id": 20, "question": "Celowo piszę komentarze z błędami.", "effects": {"prog": -2}},
    {"id": 21, "question": "Trolli nie należy karmić.", "effects": {"right": -1}},
    {"id": 22, "question": "Moimi komentarzami staram się jak najbardziej rozbawić ludzi", "effects": {"auth": -1}},
    {"id": 23, "question": "Uwielbiam kłótnie polityczne oraz rozpoczynanie ich.", "effects": {"right": -1}},
    {"id": 24, "question": "To dobrze, że trolling na większości stronach jest karany banem.", "effects": {"right": 2}},
    {"id": 25, "question": "Większość internautów uważa, iż pisze zbyt niepoważnie.", "effects": {"auth": -2}},
];
